[tox]
envlist =
    py39-lxml{48,49}

[gh-actions]
python =
    3.9: py39

[testenv:py39-lxml{48,49}]
passenv = PYTHON_VERSION
deps =
    lxml48: lxml==4.8.0
    lxml49: lxml==4.9.4
setenv =
  LC_ALL=C.UTF-8
allowlist_externals = uv, pytest
commands =
    pytest -n 4 --dist loadfile
