name: Main

on:
    push:
        branches:
            - devel

jobs:
    tox:
        name: Tox with ${{ matrix.python-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.9"]
            fail-fast: false
        steps:
            - name: Check out
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: true
                  cache-suffix: ${{ matrix.os }}-py${{ matrix.python-version }}

            - name: Setup python for test ${{ matrix.python-version }}
              run: uv python install ${{ matrix.python-version }}
              # uses: actions/setup-python@v6
              # with:
              # python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: uv sync --all-extras --dev

            - name: Test with tox
              shell: bash
              run: |
                  PY_FACTOR="py$(echo ${{ matrix.python-version }} | tr -d '.')"

                  if [ "${{ matrix.python-version }}" == "3.14" ]; then
                      # Run lint first, then environments with 'py314' factor
                      echo "Executing: tox -e lint"
                      uv run -- tox -e lint
                      echo "Executing: tox -f $PY_FACTOR"
                      uv run -- tox -f "$PY_FACTOR"
                  else
                      # Run all environments containing the factor 'py312', 'py311', etc.
                      echo "Executing: tox -f $PY_FACTOR"
                      uv run -- tox -f "$PY_FACTOR"
                  fi
